In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("spotify_millsongdata.csv")

In [ ]:
df.head(5)

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [ ]:
df.tail(5)

,artist,song,link,text
57645,Ziggy Marley,Good Old Days,/z/ziggy+marley/good+old+days_10198588.html,Irie days come on play \r\nLet the angels fly...
57646,Ziggy Marley,Hand To Mouth,/z/ziggy+marley/hand+to+mouth_20531167.html,Power to the workers \r\nMore power \r\nPowe...
57647,Zwan,Come With Me,/z/zwan/come+with+me_20148981.html,all you need \r\nis something i'll believe \...
57648,Zwan,Desire,/z/zwan/desire_20148986.html,northern star \r\nam i frightened \r\nwhere ...
57649,Zwan,Heartsong,/z/zwan/heartsong_20148991.html,come in \r\nmake yourself at home \r\ni'm a ...

In [ ]:
df.shape

(57650, 4)

In [ ]:
df.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [ ]:
df = df.sample(5000).drop('link', axis=1, errors='ignore').reset_index(drop=True)

In [ ]:
df.head(10)

,artist,song,text
0,Death,Lack Of Comprehension,a condeming fear strikes down \r things they ...
1,Loretta Lynn,After The Fire Is Gone,love is where you find it \r when you find no...
2,Westlife,Tell Me It's Love,after all the lights come down \r and the cir...
3,Iggy Pop,Plastic Concrete,"plastic and concrete, baby \r these are the f..."
4,Oingo Boingo,Dead Man's Party,i'm all dressed up with nowhere to go \r walk...
5,Grateful Dead,I Will Take You Home,little girl lost \r in a forest of dreams. \...
6,Deep Purple,Freedom,"oh, my honey, take my money \r i do what i wa..."
7,Faith No More,Digging The Grave,it would be wrong to ask you why \r because i...
8,Phineas And Ferb,Danny's Story,when i was a boy down in south illinois \r i ...
9,Lenny Kravitz,Mr Cab Driver,mr. cab driver won't you stop to let me in \r...

In [ ]:
df['text'][0]

'a condeming fear strikes down  \r things they cannot understand  \r an excuse to cover up weaknesses that lie within  \r lies  \r laying your guilt and pain  \r on people that had no part in the molding of a life  \r that creates its destruction  \r lies  \r right before your very eyes  \r a reflection of the mistakes  \r to the end you will deny  \r your part in the demise of a life  \r lack of comprehension  \r thriving on your cliche  \r compelled by self-resentment  \r   \r [solo: schuldiner]  \r   \r reaching into the minds of those that created  \r the depression in which they  \r in which they drowned their flesh and blood  \r lies  \r so easy to blame the  \r everlasting fear on a pathetic attempt  \r to justify the ending of life  \r lies  \r right before your very eyes  \r a reflection of the mistakes  \r to the end you will deny  \r your part in the demise of a life  \r lack of comprehension  \r thriving on your cliche  \r compelled by self-resentment\r \r '

In [ ]:
df.shape

(5000, 3)

Text Cleaning/Text Preprocessing

In [ ]:
df['text'] = df['text'].str.lower().replace(r'^\w\s', ' ').replace(r'\n', ' ', regex = True)

In [ ]:
df.tail(5)

,artist,song,text
4995,Robbie Williams,It's Only Us,and they want us to grow up \r we don't want ...
4996,Youngbloodz,Thangs Movin' Slow,"yeah, attic crew, attic crew and cooley see my..."
4997,Lata Mangeshkar,Aa Gaye,kaun rokega ab pyaar ka raasta \r main to pi ...
4998,Bob Dylan,I'd Have You Anytime,by bob dylan and george harrison \r \r let ...
4999,Alison Krauss,The Three Bells,album: tribute to tradition \r \r there's a...

In [ ]:
import nltk
from nltk.stem.porter import PorterStemmer

In [ ]:
stemmer = PorterStemmer()

In [ ]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\SOUMYADEEP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
def token(txt):
    token = nltk.word_tokenize(txt)
    a =[stemmer.stem(w) for w in token]
    return " ".join(a)

In [ ]:
token("you are beautiful,beauty")

'you are beauti , beauti'

In [ ]:
df['text'].apply(lambda x: token(x))

0       a condem fear strike down thing they can not u...
1       love is where you find it when you find no lov...
2       after all the light come down and the circu ha...
3       plastic and concret , babi these are the fact ...
4       i 'm all dress up with nowher to go walkin ' w...
                              ...
4995    and they want us to grow up we do n't want to ...
4996    yeah , attic crew , attic crew and cooley see ...
4997    kaun rokega ab pyaar ka raasta main to pi ki n...
4998    by bob dylan and georg harrison let me in here...
4999    album : tribut to tradit there 's a villag hid...
Name: text, Length: 5000, dtype: object

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
tfid = TfidfVectorizer(analyzer='word', stop_words='english')

In [ ]:
matrix = tfid.fit_transform(df['text'])

In [ ]:
similer = cosine_similarity(matrix)

In [ ]:
similer[0]

array([1.        , 0.00372024, 0.        , ..., 0.        , 0.        ,
       0.00425499], shape=(5000,))

In [ ]:
index = df[df['song'].str.contains('Aa Gaye', case=False, na=False)].index

print(index[0] if len(index) > 0 else "Song not found")

4997

Recommender Function

In [ ]:
def recommender(song_name):
    idx = df[df['song']==song_name].index[0]
    distance = sorted(list(enumerate(similer[idx])), reverse=True, key = lambda x:x[1])
    song = []
    for s_id in distance[1:21]:
        song.append(df.iloc[s_id[0]].song)
    return song

In [ ]:
recommender("Aa Gaye")

['More Than Life',
 'Raindrops',
 'Go Away',
 'Tiger In A Burning Tree',
 "I've Got My Love To Keep Me Warm",
 'Help Me Scrape The Mucus Off My Brain',
 "Ain't No Sunshine",
 'Anytime',
 'Genie In A Bottle',
 'Colorblind',
 'Walking On Sunshine',
 'Breath Of God',
 'Corazon De Oro',
 'Nothing Out Of Nothing',
 'When You Believe',
 "Daddy's Little Girl",
 'Grinding Gettin Money',
 'I Like Beer',
 'If Only',
 'Hold On']

In [ ]:
import pickle

In [ ]:
pickle.dump(similer, open("similarity.pkl","wb"))

In [ ]:
pickle.dump(df, open("df.pkl","wb"))